# .github/workflows/test.yml
name: Test Actions

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "✅ GitHub Actions is working!"
